/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QsExportRouteImport } from './routes/qs-export'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as ModulesModuleIdRouteImport } from './routes/modules.$moduleId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AuthSetPasswordRouteImport } from './routes/auth.set-password'
import { Route as JobsJobIdExportRouteImport } from './routes/jobs.$jobId_.export'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QsExportRoute = QsExportRouteImport.update({
  id: '/qs-export',
  path: '/qs-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => ModulesRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdExportRoute = JobsJobIdExportRouteImport.update({
  id: '/$jobId_/export',
  path: '/$jobId/export',
  getParentRoute: () => JobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intelligence': typeof IntelligenceRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRouteWithChildren
  '/qs-export': typeof QsExportRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/jobs/$jobId/export': typeof JobsJobIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/qs-export': typeof QsExportRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/jobs': typeof JobsIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/jobs/$jobId/export': typeof JobsJobIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intelligence': typeof IntelligenceRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRouteWithChildren
  '/qs-export': typeof QsExportRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/jobs/$jobId_/export': typeof JobsJobIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intelligence'
    | '/jobs'
    | '/login'
    | '/modules'
    | '/qs-export'
    | '/reports'
    | '/review'
    | '/settings'
    | '/upload'
    | '/users'
    | '/auth/set-password'
    | '/jobs/$jobId'
    | '/modules/$moduleId'
    | '/jobs/'
    | '/modules/'
    | '/jobs/$jobId/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intelligence'
    | '/login'
    | '/qs-export'
    | '/reports'
    | '/review'
    | '/settings'
    | '/upload'
    | '/users'
    | '/auth/set-password'
    | '/jobs/$jobId'
    | '/modules/$moduleId'
    | '/jobs'
    | '/modules'
    | '/jobs/$jobId/export'
  id:
    | '__root__'
    | '/'
    | '/intelligence'
    | '/jobs'
    | '/login'
    | '/modules'
    | '/qs-export'
    | '/reports'
    | '/review'
    | '/settings'
    | '/upload'
    | '/users'
    | '/auth/set-password'
    | '/jobs/$jobId'
    | '/modules/$moduleId'
    | '/jobs/'
    | '/modules/'
    | '/jobs/$jobId_/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntelligenceRoute: typeof IntelligenceRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  QsExportRoute: typeof QsExportRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  UsersRoute: typeof UsersRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qs-export': {
      id: '/qs-export'
      path: '/qs-export'
      fullPath: '/qs-export'
      preLoaderRoute: typeof QsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId_/export': {
      id: '/jobs/$jobId_/export'
      path: '/$jobId/export'
      fullPath: '/jobs/$jobId/export'
      preLoaderRoute: typeof JobsJobIdExportRouteImport
      parentRoute: typeof JobsRoute
    }
  }
}

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobsJobIdExportRoute: typeof JobsJobIdExportRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobsJobIdExportRoute: JobsJobIdExportRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface ModulesRouteChildren {
  ModulesModuleIdRoute: typeof ModulesModuleIdRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesModuleIdRoute: ModulesModuleIdRoute,
  ModulesIndexRoute: ModulesIndexRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntelligenceRoute: IntelligenceRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRouteWithChildren,
  QsExportRoute: QsExportRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  UsersRoute: UsersRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
